import { Command } from 'commander';
import { CloverClient } from '../lib/client.js';
import chalk from 'chalk';
export function reportsCommands(): Command {
  const r = new Command('reports').description('Reports');
  r.command('sales').requiredOption('--from <d>').requiredOption('--to <d>').option('--output <f>', '', 'table').action(async (o) => { try { const c = new CloverClient(); const from = new Date(o.from).getTime(); const to = new Date(o.to).getTime() + 86400000; const all = await c.listOrders({ limit: 1000 }); const orders = all.filter(x => (x.createdTime || 0) >= from && (x.createdTime || 0) < to); const total = orders.reduce((s, x) => s + (x.total || 0), 0); if (o.output === 'json') console.log(JSON.stringify({ total, count: orders.length, orders })); else { console.log(chalk.cyan('Period:'), o.from, 'to', o.to); console.log(chalk.cyan('Total:'), chalk.green('$' + (total / 100).toFixed(2))); console.log(chalk.cyan('Orders:'), orders.length); } } catch (e: any) { console.error(chalk.red(e.message)); process.exit(1); } });
  r.command('export').argument('<type>').requiredOption('--output <file>').option('--format <f>', 'json|csv', 'json').option('--limit <n>', '', '1000').action(async (t: string, o) => { try { const c = new CloverClient(); const fs = await import('fs'); let data: any[]; if (t === 'orders') data = await c.listOrders({ limit: +o.limit }); else if (t === 'items') data = await c.listItems({ limit: +o.limit }); else { console.error(chalk.red('Type: orders or items')); process.exit(1); } if (o.format === 'csv' && data.length) { const h = Object.keys(data[0]).filter(k => typeof data[0][k] !== 'object'); fs.writeFileSync(o.output, [h.join(','), ...data.map(r => h.map(k => JSON.stringify((r as any)[k] ?? '')).join(','))].join('\n')); } else fs.writeFileSync(o.output, JSON.stringify(data, null, 2)); console.log(chalk.green('Exported ' + data.length + ' to ' + o.output)); } catch (e: any) { console.error(chalk.red(e.message)); process.exit(1); } });
  return r;
}
